### ISSUE TITLE
Allow for an option to use Credential Manager

### ISSUE THREAD

**Issue by ghost** [draggeta/sysadmin-scripts#2]
Currently the only way to supply credentials is in the script. This isn't secure. Might be better to find a way to pull saved credentials from the Credential Manager.

**Comment by ghost** [comment]
Allowed for use of an encrypted file containing the password. This is quite a lot better than just having the password plaintext in the script. See https://github.com/Draggeta/Send-PasswordExpirationMail/commit/9b3d723b5067249a6c44bbf7eb646d0ae842d0b0

**Comment by Draggeta** [comment]
Option for encrypted file added in https://github.com/Draggeta/Send-PasswordExpirationMail/commit/9b3d723b5067249a6c44bbf7eb646d0ae842d0b0

**Comment by draggeta** [comment]
There are other solutions that do this and better than I could, such as https://github.com/davotronic5000/PowerShell_Credential_Manager/tree/master
